---
- name: Namespace for adventurer
  community.kubernetes.k8s:
    state: "{{ adventurer_state }}"
    name: "{{ adventurer_namespace }}"
    api_version: v1
    kind: Namespace

- name: adventurer service
  community.kubernetes.k8s:
    state: "{{ adventurer_state }}"
    namespace: "{{ adventurer_namespace }}"
    template: "{{ item }}"
  with_items:
    - accounting.yml.j2
    - bank.yml.j2
    - club.yml.j2
    - finance-jobs.yml.j2
    - finance.yml.j2
    - github.yml.j2
    - guide.yml.j2
    - hall.yml.j2
    - ingress.yml.j2
    - kanban.yml.j2
    - tower.yml.j2
  tags:
    - adventurer
