---
- name: Namespace for adv-tech
  community.kubernetes.k8s:
    state: "{{ state }}"
    name: "{{ namespace }}"
    api_version: v1
    kind: Namespace

- name: adv-tech service
  community.kubernetes.k8s:
    state: "{{ state }}"
    namespace: "{{ namespace }}"
    template: "{{ item }}"
  with_items:
    - hall.yml.j2
    - bank.yml.j2
    - finance.yml.j2
    - kanban.yml.j2
    - club.yml.j2
    - tower.yml.j2
    - ingress.yml.j2
  tags:
    - adv-tech
